countries = {
    "af":  "Afghanistan", 
    "al":  "Albania", 
    "dz":  "Algeria", 
    "as":  "American Samoa",  
    "ad":  "Andorra", 
    "ao":  "Angola",  
    "ai":  "Antigua and Barbuda", 
    "ar":  "Argentina",   
    "am":  "Armenia", 
    "aw":  "Aruba",   
    "au":  "Australia",   
    "at":  "Austria", 
    "az":  "Azerbaijan",  
    "bs":  "Bahamas, The",    
    "bh":  "Bahrain", 
    "bd":  "Bangladesh",  
    "bb":  "Barbados",    
    "by":  "Belarus", 
    "be":  "Belgium", 
    "bz":  "Belize",  
    "bj":  "Benin",   
    "bm":  "Bermuda", 
    "bt":  "Bhutan",  
    "bo":  "Bolivia", 
    "ba":  "Bosnia and Herzegovina",  
    "bw":  "Botswana",    
    "br":  "Brazil",  
    "bn":  "Brunei Darussalam",   
    "bg":  "Bulgaria",    
    "bf":  "Burkina Faso",    
    "bi":  "Burundi", 
    "kh":  "Cambodia",    
    "cm":  "Cameroon",    
    "ca":  "Canada",  
    "cv":  "Cape Verde",  
    "ky":  "Cayman Islands",  
    "cf":  "Central African Republic",    
    "td":  "Chad",    
    "cl":  "Chile",   
    "cn":  "China",   
    "co":  "Colombia",    
    "km":  "Comoros", 
    "cd":  "Congo, Dem. Rep.",
    "cg":  "Congo, Rep.",
    "cr":  "Costa Rica",  
    "ci":  "Cote d'Ivoire",   
    "hr":  "Croatia", 
    "cu":  "Cuba",    
    "cw":  "Curacao", 
    "cy":  "Cyprus",  
    "cz":  "Czech Republic",  
    "dk":  "Denmark", 
    "dj":  "Djibouti",    
    "dm":  "Dominica",    
    "do":  "Dominican Republic",  
    "ec":  "Ecuador", 
    "eg":  "Egypt, Arab Rep.",
    "sv":  "El Salvador", 
    "gq":  "Equatorial Guinea",   
    "er":  "Eritrea", 
    "ee":  "Estonia", 
    "et":  "Ethiopia",    
    "fo":  "Faeroe Islands",  
    "fj":  "Fiji",    
    "fi":  "Finland", 
    "fr":  "France",  
    "pf":  "French Polynesia",    
    "ga":  "Gabon",   
    "gm":  "Gambia, The", 
    "ge":  "Georgia", 
    "de":  "Germany", 
    "gh":  "Ghana",   
    "gr":  "Greece",  
    "gl":  "Greenland",   
    "gd":  "Grenada", 
    "gu":  "Guam",    
    "gt":  "Guatemala",   
    "gn":  "Guinea",  
    "gw":  "Guinea-Bissau",   
    "gy":  "Guyana",  
    "ht":  "Haiti",   
    "hn":  "Honduras",    
    "hk":  "Hong Kong SAR, China",    
    "hu":  "Hungary", 
    "is":  "Iceland", 
    "in":  "India",   
    "id":  "Indonesia",   
    "ir":  "Iran, Islamic Rep.",
    "iq":  "Iraq",    
    "ie":  "Ireland", 
    "im":  "Isle of Man", 
    "il":  "Israel",  
    "it":  "Italy",   
    "jm":  "Jamaica", 
    "jp":  "Japan",   
    "jo":  "Jordan",  
    "kz":  "Kazakhstan",  
    "ke":  "Kenya",   
    "ki":  "Kiribati",    
    "kp":  "Korea, Dem. Rep.",
    "kr":  "Korea, Rep.",
    "xk":  "Kosovo",  
    "kw":  "Kuwait",  
    "kg":  "Kyrgyz Republic", 
    "la":  "Lao PDR", 
    "lv":  "Latvia",  
    "lb":  "Lebanon", 
    "ls":  "Lesotho", 
    "lr":  "Liberia", 
    "ly":  "Libya",   
    "li":  "Liechtenstein",   
    "lt":  "Lithuania",   
    "lu":  "Luxembourg",  
    "mo":  "Macao SAR, China",    
    "mk":  "Macedonia, FYR",  
    "mg":  "Madagascar",  
    "mw":  "Malawi",  
    "my":  "Malaysia",    
    "mv":  "Maldives",    
    "ml":  "Mali",    
    "mt":  "Malta",   
    "mh":  "Marshall Islands",    
    "mr":  "Mauritania",  
    "mu":  "Mauritius",   
    "yt":  "Mayotte", 
    "mx":  "Mexico",  
    "fm":  "Micronesia, Fed. Sts.",
    "md":  "Moldova", 
    "mc":  "Monaco",  
    "mn":  "Mongolia",    
    "me":  "Montenegro",  
    "ma":  "Morocco", 
    "mz":  "Mozambique",  
    "mm":  "Myanmar", 
    "na":  "Namibia", 
    "np":  "Nepal",   
    "nl":  "Netherlands", 
    "nc":  "New Caledonia",   
    "nz":  "New Zealand", 
    "ni":  "Nicaragua",   
    "ne":  "Niger",   
    "ng":  "Nigeria", 
    "mp":  "Northern Mariana Islands",    
    "no":  "Norway",  
    "om":  "Oman",    
    "pk":  "Pakistan",    
    "pw":  "Palau",   
    "pa":  "Panama",  
    "pg":  "Papua New Guinea",    
    "py":  "Paraguay",    
    "pe":  "Peru",    
    "ph":  "Philippines", 
    "pl":  "Poland",  
    "pt":  "Portugal",    
    "pr":  "Puerto Rico", 
    "wa":  "Qatar",   
    "ro":  "Romania", 
    "ru":  "Russian Federation",  
    "rw":  "Rwanda",  
    "ws":  "Samoa",   
    "sm":  "San Marino",  
    "st":  "Sao Tome and Principe",   
    "sa":  "Saudi Arabia",    
    "sn":  "Senegal", 
    "rs":  "Serbia",  
    "sc":  "Seychelles",  
    "sl":  "Sierra Leone",    
    "sg":  "Singapore",   
    "sk":  "Slovak Republic", 
    "si":  "Slovenia",    
    "sb":  "Solomon Islands", 
    "so":  "Somalia", 
    "za":  "South Africa",    
    "ss":  "South", 
    "es":  "Spain",   
    "lk":  "Sri Lanka",   
    "kn":  "St. Kitts and Nevis", 
    "lc":  "St. Lucia",   
    "mf":  "St. Martin (French part)",
    "vc":  "St. Vincent and the Grenadines",  
    "sd":  "Sudan",   
    "sr":  "Suriname",    
    "sz":  "Swaziland",   
    "se":  "Sweden",  
    "ch":  "Switzerland", 
    "sy":  "Syrian Arab Republic",    
    "tj":  "Tajikistan",  
    "tz":  "Tanzania",    
    "th":  "Thailand",    
    "tp":  "Timor-Leste", 
    "tg":  "Togo",    
    "to":  "Tonga",   
    "tt":  "Trinidad and Tobago", 
    "tn":  "Tunisia", 
    "tr":  "Turkey",  
    "tm":  "Turkmenistan",    
    "tc":  "Turks and Caicos Islands",    
    "tv":  "Tuvalu",  
    "ug":  "Uganda",  
    "ua":  "Ukraine", 
    "ae":  "United Arab Emirates",    
    "uk":  "United Kingdom",  
    "us":  "United States",   
    "uy":  "Uruguay", 
    "uz":  "Uzbekistan",  
    "vu":  "Vanuatu", 
    "ve":  "Venezuela, RB",   
    "vn":  "Vietnam", 
    "vi":  "Virgin Islands (U.S.)",   
    "ps":  "West Bank and Gaza",  
    "eh":  "Western Sahara",  
    "ye":  "Yemen, Rep.",
    "zm":  "Zambia",  
    "zw":  "Zimbabwe",
}

country_mappings = {
    "gb": "uk",
}